---
title: "Turun pienaluetilastojen visualisointi R:ssä"
author: "Pyry Kantanen"
date: 2020-12-14
categories: ["paikkatieto", "visualisointi"]
tags: ["geojson", "ggplot2", "kaupunkidata", "PC-Axis", "Turku"]
output:
  blogdown::html_page:
    highlight: tango
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>


<div id="yleistä" class="section level2">
<h2>Yleistä</h2>
<p>Turun kaupunki avasi syksyllä <a href="https://data.lounaistieto.fi/data/fi/dataset/turun-kaupungin-pienaluetilastoja">2020 pienaluetilastoja</a>, jotka antavat jo ennestään saatavilla olleiden <a href="https://www.stat.fi/org/avoindata/paikkatietoaineistot/paavo.html">postinumeroaluekohtaisten tilastojen</a> ohella mahdollisuuden tarkastella <a href="https://www.avoindata.fi/data/fi/dataset/turun-kaupungin-aluejakoja">Turun kaupungin alueita</a> hienojakoisemmin kuin aiemmin on ollut mahdollista.</p>
<p>Tietoa on kirjoitushetkellä saatavilla seuraavista asioista:</p>
<ul>
<li>Rakennukset, asunnot ja vapaa-ajanasunnot: Valmistumisvuosi, hallintaperuste, talotyyppi, käyttötarkoitus, kerrosala</li>
<li>Muuttoliike ja väestönmuutokset: Kuntaan muuttaneet ja kunnasta muuttaneet, sisäinen muuttoliike, kuolleet ja syntyneet</li>
<li>Väestörakenne: Ikä, sukupuoli, kieli, veronalaiset tulot</li>
</ul>
<p>Tilastokeskuksen sivuilta löytyvän artikkelin <a href="https://www.stat.fi/artikkelit/2009/art_2009-06-08_008.html?s=3">(Tammilehto-Luode, 2009)</a> mukaan “[k]untien sisäinen aluejako on syntynyt kuntien omien tarpeiden pohjalta”. Tästä johtuen pienalueet eivät välttämättä ole alueina kovin pysyviä ja niiden käyttö ajallisen muutoksen tarkastelussa saattaisi olla hankalaa.</p>
<p>Ainakin toistaiseksi Turun kaupunki tarjoaa valmiissa muodossa ainoastaan pienaluetilastoja sekä koko kaupungin kattavia tilastoja. Kaupunkitasoista dataa on saanut jo pitkään Tilastokeskuksen sivuilta, joten varsinainen uutuusarvo liittyykin nimenomaan pienaluetilastoihin. Pienaluetilastoista voidaan tarvittaessa aggregoida ylemmän tason alueita kuten tilastoalueita ja suuralueita.</p>
<p>Pienaluetilastojen yhdistäminen karttatietoaineistoon vaatii enemmän manuaalista työtä kuin esimerkiksi Tilastokeskuksen sivuilta <a href="https://CRAN.R-project.org/package=pxweb">pxweb-paketilla</a> ladatun tiedon visualisointi <a href="https://ropengov.org/fi/2020/02/r-paketti-geofi-tilastokeskuksen-avointen-paikkatietoaineistojen-k%C3%A4ytt%C3%B6%C3%B6n/">geofi-pakettia</a> käyttämällä. Tähän saadaan tulevaisuudessa mahdollisesti muutos, mutta tämän blogitekstin on tarkoitus demonstroida nykyhetkessä, kuinka helppoa datan visualisointi on ilman erikoistuneita pakettejakin.</p>
</div>
<div id="pienaluetilastojen-lataaminen-ja-visualisointi" class="section level2">
<h2>Pienaluetilastojen lataaminen ja visualisointi</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># px-muotoisen datan lukemiseen tarvittava paketti</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pxR)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Datan käsittelyyn tarvittavat tidyverse-paketit</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Geospatiaalisen datan käsittelyyn tarvittavat paketit</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Käytän tässä kirjoituksessa pxR-pakettia, sillä ainakin toistaiseksi Turun kaupunki toimittaa pienaluetilastonsa px-muodossa. Px-tiedostomuoto on moniulotteisen tilastotaulukon eli kuution tallennusformaatti, josta voi saada jonkinlaista lisätietoa esimerkiksi vuonna 2008 julkaistusta <a href="http://www.tilastokeskus.fi/tup/pcaxis/px-file_format_2008_1_2008-02-04_fi.pdf">käsikirjasta</a>. Px-dataa voidaan Windows-koneilla käsitellä erillisellä PxWin-ohjelmistolla, mutta Macin tai Linuxin käyttäjille tämä ei valitettavasti ole vaihtoehto.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># URL lähde: https://www.avoindata.fi/data/fi/dataset/turun-kaupungin-pienaluetilastoja</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>url_data <span class="ot">&lt;-</span> <span class="st">&quot;https://dev.turku.fi/datasets/pienaluetilastot/turku-vaesto_ian_ja_sukupuolen_mukaan-varak_12nh.px&quot;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># pxR-paketin standardinomainen tapa lukea Tilastokeskuksen px-dataa ei toimi:</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># read.px(filename = url)</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Error in scan(tc, na.strings = na.strings, quote = NULL, quiet = TRUE) : </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  scan() expected &#39;a real&#39;, got &#39;..&#39;</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Käytetään argumenttia na.strings = c(&quot;..&quot;), jolloin data voidaan lukea</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>px_data <span class="ot">&lt;-</span> <span class="fu">read.px</span>(url_data, <span class="at">na.strings =</span> <span class="fu">c</span>(<span class="st">&quot;..&quot;</span>))</span></code></pre></div>
<p>Vuoden 2008 PC-Axis-tiedostomuodon käsikirjasta voidaan lukea, että pistekoodi “..” tarkoittaa tietoa, jota ei ole saatu, joka on epävarmaa tai joka on salassapitosäännön alaista. Turun kaupungin julkaisemien tietoaineistojen kuvauksen yhteydessä kerrotaan, että “Turun kaupungin avoimen datan palvelu on sopimus- ja tietosuojasyistä rajannut aineistojen laajuutta. Julkaistuilla alueilla on vähintään 100 asukasta tai 10 rakennusta tilastosta riippuen.” Puuttuvan tiedon voikin suurimmalti osalti selittää tällä rajauksella, mistä johtuen kahden pisteen pistekoodi lienee tullut valituksi.</p>
<p>Tarkastellaan seuraavaksi lataamamme px_data-objektin sisältöä:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># px_data-objektin sisältämät avainsanat</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(px_data)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="do">##  [1] &quot;AXIS.VERSION&quot;        &quot;CHARSET&quot;             &quot;CODEPAGE&quot;           </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="do">##  [4] &quot;CODES&quot;               &quot;CODES.sv.&quot;           &quot;CONTACT&quot;            </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="do">##  [7] &quot;CONTACT.sv.&quot;         &quot;CONTENTS&quot;            &quot;CONTENTS.sv.&quot;       </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [10] &quot;CONTVARIABLE&quot;        &quot;CONTVARIABLE.sv.&quot;    &quot;COPYRIGHT&quot;          </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="do">## [13] &quot;CREATION.DATE&quot;       &quot;DATA&quot;                &quot;DECIMALS&quot;           </span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [16] &quot;DESCRIPTION&quot;         &quot;DESCRIPTION.sv.&quot;     &quot;DOMAIN&quot;             </span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="do">## [19] &quot;DOMAIN.sv.&quot;          &quot;HEADING&quot;             &quot;HEADING.sv.&quot;        </span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="do">## [22] &quot;LANGUAGE&quot;            &quot;LANGUAGES&quot;           &quot;LAST.UPDATED&quot;       </span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="do">## [25] &quot;LAST.UPDATED.sv.&quot;    &quot;MADE.WITH&quot;           &quot;MATRIX&quot;             </span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="do">## [28] &quot;NOTE&quot;                &quot;NOTE.sv.&quot;            &quot;OFFICIAL.STATISTICS&quot;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="do">## [31] &quot;SHOWDECIMALS&quot;        &quot;SOURCE&quot;              &quot;SOURCE.sv.&quot;         </span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="do">## [34] &quot;STUB&quot;                &quot;STUB.sv.&quot;            &quot;SUBJECT.AREA&quot;       </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="do">## [37] &quot;SUBJECT.AREA.sv.&quot;    &quot;SUBJECT.CODE&quot;        &quot;TABLEID&quot;            </span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="do">## [40] &quot;TIMEVAL&quot;             &quot;TIMEVAL.sv.&quot;         &quot;TITLE&quot;              </span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="do">## [43] &quot;TITLE.sv.&quot;           &quot;UNITS&quot;               &quot;UNITS.sv.&quot;          </span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="do">## [46] &quot;VALUES&quot;              &quot;VALUES.sv.&quot;          &quot;VARIABLE.TYPE&quot;      </span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="do">## [49] &quot;VARIABLE.TYPE.sv.&quot;</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># px_data-objektin luokka</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(px_data)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># [1] &quot;px&quot;</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co"># px_data-objektin rakenne: Tulostaa erittäin pitkän listan tietoja, jota en toista tässä esimerkissä</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(px_data)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Muoto, jossa px_data-objektin tiedot on tallennettu</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(px_data)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co"># [1] &quot;list&quot;</span></span></code></pre></div>
<p>Huomataan, että suurin osa px_data-objektin sisällöstä on erilaista metatietoa, joka on tietojen raportoinnin kannalta yleensä hyvä ottaa huomioon. Olennaisin tieto löytyy kuitenkin jo otsikosta: Väestön määrä jaoteltuna iän (1 vuoden tarkkuudella), sukupuolen ja kielen mukaan Turun eri osa-alueilla. Numeerisen tilastotiedon tarkastelun ja visualisoinnin kannalta kiinnostavin sisältö löytyy DATA-avainsanan takaa. DATA-elementti sisältää vastaavasti data.framen nimeltä value, josta olemme kiinnostuneita.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Muodostetaan uusi muuttuja turku_data px_data-objektin sisältämästä data.framesta</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>turku_data <span class="ot">&lt;-</span> px_data<span class="sc">$</span>DATA<span class="sc">$</span>value</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># px_data -objektin kuvauksen tallentaminen voi olla hyödyllistä myöhemmin</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>turku_data_otsikko <span class="ot">&lt;-</span> px_data<span class="sc">$</span>DESCRIPTION<span class="sc">$</span>value</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>turku_data_otsikko</span></code></pre></div>
<pre><code>## [1] &quot;12nh -- Väestö iän (1-v.), sukupuolen ja kielen mukaan kunnan osa-alueittain, 2019&quot;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(turku_data)</span></code></pre></div>
<pre><code>## [1] 160344      7</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(turku_data)</span></code></pre></div>
<pre><code>##            Tiedot        Vuosi                            Kieli      
##  Väestö 31.12.:160344   2019:160344   Yhteensä               :40086  
##                                       suomi                  :40086  
##                                       ruotsi                 :40086  
##                                       VIERASKIELISET YHTEENSÄ:40086  
##                                                                      
##                                                                      
##                                                                      
##     Sukupuoli           Ikä                                   Osa.alue     
##  Yhteensä:53448   Yhteensä:  1572   853 Turku                     :  1224  
##  Miehet  :53448   0       :  1572   853101001 Rauhankatu VII      :  1224  
##  Naiset  :53448   1       :  1572   853101002 Ursininkatu pohj.   :  1224  
##                   2       :  1572   853101003 Ursininkatu et.     :  1224  
##                   3       :  1572   853101004 Kristiinankatu et.  :  1224  
##                   4       :  1572   853101005 Kristiinankatu pohj.:  1224  
##                   (Other) :150912   (Other)                       :153000  
##      value          
##  Min.   :     0.00  
##  1st Qu.:     0.00  
##  Median :     1.00  
##  Mean   :    22.68  
##  3rd Qu.:     7.00  
##  Max.   :192962.00  
##  NA&#39;s   :24480</code></pre>
<p>dim-komennon tulos kertoo, että data.framessa on 160344 riviä ja 7 saraketta. Summaryn tulkitseminen on tässä yhteydessä hieman hankalampaa, mutta käytännössä luvut kertovat, kuinka monta kertaa kukin uniikki rivi esiintyy tässä pitkässä muodossa olevassa taulukossa. Numeroista ei siis voi tehdä päätelmiä minkään ryhmän jäsenten lukumäärästä vaan ennemmin siitä, kuinka monta kertaa kukin muuttuja esiintyy taulukossa.</p>
<p>Olemme tällä kertaa kiinnostuneita eri pienalueiden tiedoista. Visualisoinnin yksinkertaistamiseksi tarkastelemme eri kieliryhmiin kuuluvia eri pienalueilla, joten valitsemme siis Kieli-sarakkeesta suomi, ruotsi ja vieraskieliset. Sukupuolen tai iän osalta emme tee erottelua. Osa.alue-sarakkeesta voimme ottaa kaikki tiedot, sillä rajaukset voidaan tehdä samalla kun tilastotietoja yhdistetään paikkatietoon</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>turku_data2 <span class="ot">&lt;-</span> turku_data <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sukupuoli <span class="sc">==</span> <span class="st">&quot;Yhteensä&quot;</span>, Kieli <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;VIERASKIELISET YHTEENSÄ&quot;</span>, <span class="st">&quot;ruotsi&quot;</span>, <span class="st">&quot;suomi&quot;</span>), Ikä <span class="sc">==</span> <span class="st">&quot;Yhteensä&quot;</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(turku_data2)</span></code></pre></div>
<pre><code>##            Tiedot     Vuosi                         Kieli        Sukupuoli  
##  Väestö 31.12.:393   2019:393   Yhteensä               :  0   Yhteensä:393  
##                                 suomi                  :131   Miehet  :  0  
##                                 ruotsi                 :131   Naiset  :  0  
##                                 VIERASKIELISET YHTEENSÄ:131                 
##                                                                             
##                                                                             
##                                                                             
##        Ikä                                Osa.alue       value       
##  Yhteensä:393   853 Turku                     :  3   Min.   :     0  
##  0       :  0   853101001 Rauhankatu VII      :  3   1st Qu.:    48  
##  1       :  0   853101002 Ursininkatu pohj.   :  3   Median :   134  
##  2       :  0   853101003 Ursininkatu et.     :  3   Mean   :  1157  
##  3       :  0   853101004 Kristiinankatu et.  :  3   3rd Qu.:   710  
##  4       :  0   853101005 Kristiinankatu pohj.:  3   Max.   :159506  
##  (Other) :  0   (Other)                       :375   NA&#39;s   :60</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Muutetaan vieraskielisten teksti lyhyemmäksi</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>turku_data2<span class="sc">$</span>Kieli <span class="ot">&lt;-</span> turku_data2<span class="sc">$</span>Kieli <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recode</span>(<span class="st">&quot;VIERASKIELISET YHTEENSÄ&quot;</span> <span class="ot">=</span> <span class="st">&quot;muut&quot;</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Luodaan uusi muuttuja area_code poistamalla Osa.alue-muuttujasta aakkoset, välimerkit ja välilyönnit</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>turku_data2 <span class="ot">&lt;-</span> turku_data2 <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">area_code =</span> <span class="fu">gsub</span>(<span class="st">&quot;[[:alpha:]]*[[:punct:]]*[[:blank:]]*&quot;</span>, <span class="st">&quot;&quot;</span>, turku_data2<span class="sc">$</span>Osa.alue))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Muutetaan pitkä datamuoto leveäksi</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>turku_data2 <span class="ot">&lt;-</span> turku_data2 <span class="sc">%&gt;%</span> </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">&quot;Osa.alue&quot;</span>, <span class="st">&quot;area_code&quot;</span>), <span class="at">names_from =</span> <span class="st">&quot;Kieli&quot;</span>, <span class="at">values_from =</span> <span class="st">&quot;value&quot;</span>)</span></code></pre></div>
<p>Seuraavaksi yhdistämme datatiedot geospatiaaliseen dataan käyttämällä sf-pakettia sekä visualisointiin ggplot2-pakettia.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>url_geo <span class="ot">&lt;-</span> <span class="st">&quot;http://dev.turku.fi/datasets/aluejaot/pienalueet-4326.geojson&quot;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>turku_pienalueet <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> url_geo)</span></code></pre></div>
<pre><code>## Reading layer `aj_osa-alue_20200415_area&#39; from data source `http://dev.turku.fi/datasets/aluejaot/pienalueet-4326.geojson&#39; using driver `GeoJSON&#39;
## Simple feature collection with 129 features and 1 field
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 22.06614 ymin: 60.33351 xmax: 22.45816 ymax: 60.73729
## geographic CRS: WGS 84</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>turku_pienalueet <span class="ot">&lt;-</span> turku_pienalueet <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area_code =</span> <span class="fu">gsub</span>(<span class="st">&quot;[[:alpha:]]*[[:punct:]]*[[:blank:]]*&quot;</span>, <span class="st">&quot;&quot;</span>, turku_pienalueet<span class="sc">$</span>id))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(turku_pienalueet, turku_data2, <span class="at">by =</span> <span class="st">&quot;area_code&quot;</span>)</span></code></pre></div>
<p>Visualisoidaan ruotsinkielisen väestön osuus suhteessa suomenkielisiin ja muunkielisiin:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ruotsi <span class="sc">/</span> (suomi <span class="sc">+</span> ruotsi <span class="sc">+</span> muut)), <span class="at">color =</span> <span class="fu">alpha</span>(<span class="st">&quot;white&quot;</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">&quot;Ruotsinkielisten osuus&quot;</span>)</span></code></pre></div>
<p><img src="/post/2020-12-14-turku-datan-visualisointi.fi_files/figure-html/visualization-1.png" width="672" /></p>
<p>Kuten huomataan, osalla pienalueista dataa on liian vähän visualisointien tekemiseen. Toisaalta pienalueet ovat visualisoimisen kannalta ongelmallisia siinäkin mielessä, että karttakuva on helposti liian yksityiskohtaista piiperrystä. Eräs ratkaisu tähän olisi tehdä pienaluekuvista kartogrammi, jossa väkirikkaammat pienalueet piirrettäisiin suhteellisesti suurempina kuin harvaan asutummat pienalueet. Tällöin kartan maantieteellinen vastaavuus kuitenkin vääristyisi ja “karttakuva” muuttuisi entistä abstraktimman tason visualisoinniksi.</p>
<p>Toinen ratkaisu on muodostaa pienaluetilastoista suurempia alueita ryhmittelemällä ne uudelleen.</p>
</div>
<div id="pienalueiden-uudelleenryhmittely-tilastoalueiksi-ja-suuralueiksi" class="section level2">
<h2>Pienalueiden uudelleenryhmittely tilastoalueiksi ja suuralueiksi</h2>
<p>Turku voidaan jakaa 9 suuralueeseen, 45 tilastoalueesta ja 129 pienalueesta. Jokainen suuralue sisältää useamman tilastoalueen ja useimmat tilastoalueet sisältävät useita pienalueita. Joidenkin ilmeisesti harvaan asuttujen alueiden tapauksessa tilastoalueet sisältävät ainoastaan yhden pienalueen. Turun kaupungin tilastoaluejakoa voi tarkastella tästä kartasta: <a href="https://www.turku.fi/sites/default/files/atoms/files/tilastoaluejakokartta_tilusvaihtojen_ja_kuntarajamuutoksen_takia_10032020_0.pdf" class="uri">https://www.turku.fi/sites/default/files/atoms/files/tilastoaluejakokartta_tilusvaihtojen_ja_kuntarajamuutoksen_takia_10032020_0.pdf</a></p>
<p>Useimmat aiemmin muodostetut aluekoodit muodostuvat 9 numerosta, esimerkkinä “853943130 Saramäki - Paimala”. 853 on Turun kaupungin kuntakoodi, 9 on Maaria-Paattisen suuralueen numero, 43 on Etelä-Maarian tilastoalueen numero ja 130 on Saramäki-Paimalan pienaluekoodi. Koska numerosarja on kaikkien tapausten osalta saman pituinen ja eri alueita merkitsevät numerot ovat aina samassa kohdassa, koodi pystytään helposti purkamaan osiin:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>suuralue <span class="ot">&lt;-</span> <span class="fu">substring</span>(dat<span class="sc">$</span>area_code, <span class="at">first =</span> <span class="dv">4</span>, <span class="at">last =</span> <span class="dv">4</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>tilastoalue <span class="ot">&lt;-</span> <span class="fu">substring</span>(dat<span class="sc">$</span>area_code, <span class="at">first =</span> <span class="dv">5</span>, <span class="at">last =</span> <span class="dv">6</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>pienalue <span class="ot">&lt;-</span> <span class="fu">substring</span>(dat<span class="sc">$</span>area_code, <span class="at">first =</span> <span class="dv">7</span>, <span class="at">last =</span> <span class="dv">9</span>)</span></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dat_suuralue <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">group_by</span>(suuralue) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">suomi =</span> <span class="fu">sum</span>(suomi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">ruotsi =</span> <span class="fu">sum</span>(ruotsi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">muut =</span> <span class="fu">sum</span>(muut, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dat_tilastoalue <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">group_by</span>(tilastoalue) <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">suomi =</span> <span class="fu">sum</span>(suomi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">ruotsi =</span> <span class="fu">sum</span>(ruotsi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">muut =</span> <span class="fu">sum</span>(muut, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>Lopuksi visualisoidaan:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_suuralue) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ruotsi <span class="sc">/</span> (suomi <span class="sc">+</span> ruotsi <span class="sc">+</span> muut)), <span class="at">color =</span> <span class="fu">alpha</span>(<span class="st">&quot;white&quot;</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">&quot;Ruotsinkielisten osuus&quot;</span>)</span></code></pre></div>
<p><img src="/post/2020-12-14-turku-datan-visualisointi.fi_files/figure-html/visualization2-1.png" width="672" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_tilastoalue) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ruotsi <span class="sc">/</span> (suomi <span class="sc">+</span> ruotsi <span class="sc">+</span> muut)), <span class="at">color =</span> <span class="fu">alpha</span>(<span class="st">&quot;white&quot;</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">&quot;Ruotsinkielisten osuus&quot;</span>)</span></code></pre></div>
<p><img src="/post/2020-12-14-turku-datan-visualisointi.fi_files/figure-html/visualization2-2.png" width="672" /></p>
<p>Hyvännäköinen karttakuva vaatisi informatiivisuuden vuoksi lisää tietoja, erityisesti alueiden nimet sisältävät labelit. Px-data ei sisältänyt kuin pienalueiden nimet, joten tilastoalueiden ja suuralueiden nimet joutuu kirjoittamaan joko käsin tai lataamaan toisesta lähteestä. Tätä blogikirjoitusta varten tein Turun kaupungin aluejaot sisältävän pdf-kartan pohjalta csv-tiedoston, joka sisältää alueiden numerokoodit ja nimet. Aiemmasta jaottelusta poiketen numerokoodit ovat hieman pidempiä, joten muokkaamme dat-objektin koodit csv-tiedostoa vastaaviksi:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>pienalue <span class="ot">&lt;-</span> <span class="fu">paste</span>(dat<span class="sc">$</span>suuralue, dat<span class="sc">$</span>tilastoalue, dat<span class="sc">$</span>pienalue, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>tilastoalue <span class="ot">&lt;-</span> <span class="fu">paste</span>(dat<span class="sc">$</span>suuralue, dat<span class="sc">$</span>tilastoalue, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>dat_tilastoalue <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">group_by</span>(tilastoalue) <span class="sc">%&gt;%</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">suomi =</span> <span class="fu">sum</span>(suomi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">ruotsi =</span> <span class="fu">sum</span>(ruotsi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">muut =</span> <span class="fu">sum</span>(muut, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Luetaan sisään csv-tiedosto, jossa ei ole otsakeriviä</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>aluekoodit <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;turku_alueet.csv&quot;</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(aluekoodit)</span></code></pre></div>
<pre><code>##                           V1
## 1     1 Suuralue 1: Keskusta
## 2              101 VI ja VII
## 3      101001 Rauhankatu VII
## 4  101002 Ursininkatu pohj. 
## 5     101003 Ursininkatu et.
## 6 101004 Kristiinankatu et.</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poistetaan rivien alusta numero + välilyönti ja muodostetaan uusi sarake</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>aluekoodit<span class="sc">$</span>nimi <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">&quot;^[0-9]*[[:blank:]]&quot;</span>, <span class="st">&quot;&quot;</span>, aluekoodit<span class="sc">$</span>V1)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Muodostetaan uusi muuttuja x1, joka sisältää alun numeroiden + välilyönnin merkkimäärän</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">regexpr</span>(<span class="st">&quot;^[0-9]*&quot;</span>, aluekoodit<span class="sc">$</span>V1)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Käytetään tietoa merkkimäärästä hyväksi alun numerokoodeja poimittaessa</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>aluekoodit<span class="sc">$</span>numero <span class="ot">&lt;-</span> <span class="fu">regmatches</span>(aluekoodit<span class="sc">$</span>V1, x1)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Yhdistetään aluekoodit-muuttujan nimet dat-objekteihin numeroiden perusteella</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>dat_suuralue <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(dat_suuralue, aluekoodit, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;suuralue&quot;</span> <span class="ot">=</span> <span class="st">&quot;numero&quot;</span>))</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>dat_tilastoalue <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(dat_tilastoalue, aluekoodit, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;tilastoalue&quot;</span> <span class="ot">=</span> <span class="st">&quot;numero&quot;</span>))</span></code></pre></div>
<p>Visualisoinnit labeleiden kanssa:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_suuralue) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ruotsi <span class="sc">/</span> (suomi <span class="sc">+</span> ruotsi <span class="sc">+</span> muut)), <span class="at">color =</span> <span class="fu">alpha</span>(<span class="st">&quot;white&quot;</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> nimi), <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">check_overlap =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">&quot;Ruotsinkielisten osuus&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<p><img src="/post/2020-12-14-turku-datan-visualisointi.fi_files/figure-html/visualization3-1.png" width="672" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_tilastoalue) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ruotsi <span class="sc">/</span> (suomi <span class="sc">+</span> ruotsi <span class="sc">+</span> muut)), <span class="at">color =</span> <span class="fu">alpha</span>(<span class="st">&quot;white&quot;</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf_label</span>(<span class="fu">aes</span>(<span class="at">label =</span> nimi), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">&quot;Ruotsinkielisten osuus&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<p><img src="/post/2020-12-14-turku-datan-visualisointi.fi_files/figure-html/visualization3-2.png" width="672" /></p>
<p>Kuten huomataan, suuri määrä tekstiä tai labeleita saa kartan näyttämään sotkuiselta. Teemakartat ovatkin kaikista hyödyllisimmillään alueellisten trendien, esimerkiksi työttömyysasteen tai asukkaiden keski-iän nopeaan silmäilyyn, jolloin alueen nimikkeellä ei välttämättä ole niin suurta merkitystä.</p>
<p>Toisaalta nimikkeiden kiinnittäminen paikkatietoon ei myöskään ole turhaa, jos paikkatietoja haluaa visualisoida staattisten karttojen sijaan interaktiivisessa näkymässä. Tällöin informaatiota voidaan esittää pop-up -ikkunassa ja labeleiden tekstiä voidaan samalla muotoilla monipuolisesti html-tageja käyttäen.</p>
</div>
